[features]
seeds = false
[programs.localnet]
coin_flip = "BKK5xdTQdyYsvvftniqTp4B32kcG3cYSB5peR3T8zUkR"
[programs.devnet]
coin_flip = "BKK5xdTQdyYsvvftniqTp4B32kcG3cYSB5peR3T8zUkR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/Hoc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
